### ISSUE TITLE
Criar o diagrama de classe de todo sistema com métodos, atributos e relacionamentos

### ISSUE THREAD

**Issue by victorvmc** [victorvmc/ManaFit#6]
- [x] Definir as classes utilizadas pelo sistema.
- [x] Definir os atributos e métodos de cada classe.
- [x] Definir como as classes se relacionam.
- [x] Criar diagrama de classe

**Comment by victorvmc** [comment]
- [ ] Definir as classes utilizadas pelo sistema.
- [ ] Definir os atributos e métodos de cada classe.
- [ ] Definir como as classes se relacionam.
